version: 2
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X beryju.org/korb/cmd.Version={{.Version}}'
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 'arm'
  binary: '{{ .ProjectName }}'
archives:
- id: raw
  formats: binary
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
- id: tar
  formats: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
homebrew_casks:
- ids:
    - raw
  commit_author:
    name: goreleaserbot
    email: goreleaser@beryju.org
  repository:
    owner: beryju
    name: homebrew-tap
  homepage: 'https://github.com/beryju/{{ .ProjectName }}'
  description: 'Move Kubernetes PVCs between Storage Classes and Namespaces'
  hooks:
    post:
      install: |
        if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/{{ .ProjectName }}"]
        end
