# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X beryju.org/korb/cmd.Version={{.Version}}'
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 'arm'
  binary: '{{ .ProjectName }}'
archives:
- id: raw
  format: binary
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
- id: tar
  format: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
brews:
  - ids:
      - raw
    repository:
      owner: beryju
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@beryju.org
    homepage: 'https://github.com/beryju/korb'
    description: 'Move Kubernetes PVCs between Storage Classes and Namespaces'
    directory: Formula
